/*
 * LoginIB API REST v1
 * API REST per interactuar amb el servei de LoginIB.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.login.loginib.api.client.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import org.fundaciobit.pluginsib.login.loginib.api.client.v1.model.RDatosRepresentante;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RDatosAutenticacion
 */
@JsonPropertyOrder({
  RDatosAutenticacion.JSON_PROPERTY_ID_SESION,
  RDatosAutenticacion.JSON_PROPERTY_METODO_AUTENTICACION,
  RDatosAutenticacion.JSON_PROPERTY_QAA,
  RDatosAutenticacion.JSON_PROPERTY_NIF,
  RDatosAutenticacion.JSON_PROPERTY_NOMBRE,
  RDatosAutenticacion.JSON_PROPERTY_APELLIDOS,
  RDatosAutenticacion.JSON_PROPERTY_APELLIDO1,
  RDatosAutenticacion.JSON_PROPERTY_APELLIDO2,
  RDatosAutenticacion.JSON_PROPERTY_REPRESENTANTE,
  RDatosAutenticacion.JSON_PROPERTY_PARAMS_APP
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RDatosAutenticacion {
  public static final String JSON_PROPERTY_ID_SESION = "idSesion";
  @javax.annotation.Nonnull
  private String idSesion;

  public static final String JSON_PROPERTY_METODO_AUTENTICACION = "metodoAutenticacion";
  @javax.annotation.Nonnull
  private String metodoAutenticacion;

  public static final String JSON_PROPERTY_QAA = "qaa";
  @javax.annotation.Nonnull
  private String qaa;

  public static final String JSON_PROPERTY_NIF = "nif";
  @javax.annotation.Nonnull
  private String nif;

  public static final String JSON_PROPERTY_NOMBRE = "nombre";
  @javax.annotation.Nonnull
  private String nombre;

  public static final String JSON_PROPERTY_APELLIDOS = "apellidos";
  @javax.annotation.Nullable
  private String apellidos;

  public static final String JSON_PROPERTY_APELLIDO1 = "apellido1";
  @javax.annotation.Nullable
  private String apellido1;

  public static final String JSON_PROPERTY_APELLIDO2 = "apellido2";
  @javax.annotation.Nullable
  private String apellido2;

  public static final String JSON_PROPERTY_REPRESENTANTE = "representante";
  @javax.annotation.Nullable
  private RDatosRepresentante representante;

  public static final String JSON_PROPERTY_PARAMS_APP = "paramsApp";
  @javax.annotation.Nullable
  private Map<String, String> paramsApp = new HashMap<>();

  public RDatosAutenticacion() {
  }

  public RDatosAutenticacion idSesion(@javax.annotation.Nonnull String idSesion) {
    
    this.idSesion = idSesion;
    return this;
  }

  /**
   * Identificador sesión autenticación
   * @return idSesion
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID_SESION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIdSesion() {
    return idSesion;
  }


  @JsonProperty(JSON_PROPERTY_ID_SESION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdSesion(@javax.annotation.Nonnull String idSesion) {
    this.idSesion = idSesion;
  }

  public RDatosAutenticacion metodoAutenticacion(@javax.annotation.Nonnull String metodoAutenticacion) {
    
    this.metodoAutenticacion = metodoAutenticacion;
    return this;
  }

  /**
   * Metodo autenticacion (Valores: ANONIMO;CLAVE_CERTIFICADO;CLAVE_PIN;CLAVE_PERMANENTE;CLAVE_MOVIL;CLIENTCERT;USUARIO_PASSWORD)
   * @return metodoAutenticacion
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_METODO_AUTENTICACION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMetodoAutenticacion() {
    return metodoAutenticacion;
  }


  @JsonProperty(JSON_PROPERTY_METODO_AUTENTICACION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMetodoAutenticacion(@javax.annotation.Nonnull String metodoAutenticacion) {
    this.metodoAutenticacion = metodoAutenticacion;
  }

  public RDatosAutenticacion qaa(@javax.annotation.Nonnull String qaa) {
    
    this.qaa = qaa;
    return this;
  }

  /**
   * QAA (Débil:0 / Bajo:1 / Medio: 2 / Alto: 3)
   * @return qaa
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_QAA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getQaa() {
    return qaa;
  }


  @JsonProperty(JSON_PROPERTY_QAA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQaa(@javax.annotation.Nonnull String qaa) {
    this.qaa = qaa;
  }

  public RDatosAutenticacion nif(@javax.annotation.Nonnull String nif) {
    
    this.nif = nif;
    return this;
  }

  /**
   * Nif
   * @return nif
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NIF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNif() {
    return nif;
  }


  @JsonProperty(JSON_PROPERTY_NIF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNif(@javax.annotation.Nonnull String nif) {
    this.nif = nif;
  }

  public RDatosAutenticacion nombre(@javax.annotation.Nonnull String nombre) {
    
    this.nombre = nombre;
    return this;
  }

  /**
   * Nombre
   * @return nombre
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NOMBRE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNombre() {
    return nombre;
  }


  @JsonProperty(JSON_PROPERTY_NOMBRE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNombre(@javax.annotation.Nonnull String nombre) {
    this.nombre = nombre;
  }

  public RDatosAutenticacion apellidos(@javax.annotation.Nullable String apellidos) {
    
    this.apellidos = apellidos;
    return this;
  }

  /**
   * Apellidos
   * @return apellidos
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APELLIDOS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getApellidos() {
    return apellidos;
  }


  @JsonProperty(JSON_PROPERTY_APELLIDOS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApellidos(@javax.annotation.Nullable String apellidos) {
    this.apellidos = apellidos;
  }

  public RDatosAutenticacion apellido1(@javax.annotation.Nullable String apellido1) {
    
    this.apellido1 = apellido1;
    return this;
  }

  /**
   * Apellido 1
   * @return apellido1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APELLIDO1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getApellido1() {
    return apellido1;
  }


  @JsonProperty(JSON_PROPERTY_APELLIDO1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApellido1(@javax.annotation.Nullable String apellido1) {
    this.apellido1 = apellido1;
  }

  public RDatosAutenticacion apellido2(@javax.annotation.Nullable String apellido2) {
    
    this.apellido2 = apellido2;
    return this;
  }

  /**
   * Apellido 2
   * @return apellido2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APELLIDO2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getApellido2() {
    return apellido2;
  }


  @JsonProperty(JSON_PROPERTY_APELLIDO2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApellido2(@javax.annotation.Nullable String apellido2) {
    this.apellido2 = apellido2;
  }

  public RDatosAutenticacion representante(@javax.annotation.Nullable RDatosRepresentante representante) {
    
    this.representante = representante;
    return this;
  }

  /**
   * Get representante
   * @return representante
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPRESENTANTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RDatosRepresentante getRepresentante() {
    return representante;
  }


  @JsonProperty(JSON_PROPERTY_REPRESENTANTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepresentante(@javax.annotation.Nullable RDatosRepresentante representante) {
    this.representante = representante;
  }

  public RDatosAutenticacion paramsApp(@javax.annotation.Nullable Map<String, String> paramsApp) {
    
    this.paramsApp = paramsApp;
    return this;
  }

  public RDatosAutenticacion putParamsAppItem(String key, String paramsAppItem) {
    if (this.paramsApp == null) {
      this.paramsApp = new HashMap<>();
    }
    this.paramsApp.put(key, paramsAppItem);
    return this;
  }

  /**
   * Params APP
   * @return paramsApp
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARAMS_APP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getParamsApp() {
    return paramsApp;
  }


  @JsonProperty(JSON_PROPERTY_PARAMS_APP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParamsApp(@javax.annotation.Nullable Map<String, String> paramsApp) {
    this.paramsApp = paramsApp;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RDatosAutenticacion rdatosAutenticacion = (RDatosAutenticacion) o;
    return Objects.equals(this.idSesion, rdatosAutenticacion.idSesion) &&
        Objects.equals(this.metodoAutenticacion, rdatosAutenticacion.metodoAutenticacion) &&
        Objects.equals(this.qaa, rdatosAutenticacion.qaa) &&
        Objects.equals(this.nif, rdatosAutenticacion.nif) &&
        Objects.equals(this.nombre, rdatosAutenticacion.nombre) &&
        Objects.equals(this.apellidos, rdatosAutenticacion.apellidos) &&
        Objects.equals(this.apellido1, rdatosAutenticacion.apellido1) &&
        Objects.equals(this.apellido2, rdatosAutenticacion.apellido2) &&
        Objects.equals(this.representante, rdatosAutenticacion.representante) &&
        Objects.equals(this.paramsApp, rdatosAutenticacion.paramsApp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idSesion, metodoAutenticacion, qaa, nif, nombre, apellidos, apellido1, apellido2, representante, paramsApp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RDatosAutenticacion {\n");
    sb.append("    idSesion: ").append(toIndentedString(idSesion)).append("\n");
    sb.append("    metodoAutenticacion: ").append(toIndentedString(metodoAutenticacion)).append("\n");
    sb.append("    qaa: ").append(toIndentedString(qaa)).append("\n");
    sb.append("    nif: ").append(toIndentedString(nif)).append("\n");
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    apellidos: ").append(toIndentedString(apellidos)).append("\n");
    sb.append("    apellido1: ").append(toIndentedString(apellido1)).append("\n");
    sb.append("    apellido2: ").append(toIndentedString(apellido2)).append("\n");
    sb.append("    representante: ").append(toIndentedString(representante)).append("\n");
    sb.append("    paramsApp: ").append(toIndentedString(paramsApp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

