/*
 * LoginIB API REST v1
 * API REST per interactuar amb el servei de LoginIB.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.login.loginib.api.client.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Representante en caso de persona jurídica
 */
@JsonPropertyOrder({
  RDatosRepresentante.JSON_PROPERTY_NIF,
  RDatosRepresentante.JSON_PROPERTY_NOMBRE,
  RDatosRepresentante.JSON_PROPERTY_APELLIDOS,
  RDatosRepresentante.JSON_PROPERTY_APELLIDO1,
  RDatosRepresentante.JSON_PROPERTY_APELLIDO2
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RDatosRepresentante {
  public static final String JSON_PROPERTY_NIF = "nif";
  @javax.annotation.Nonnull
  private String nif;

  public static final String JSON_PROPERTY_NOMBRE = "nombre";
  @javax.annotation.Nonnull
  private String nombre;

  public static final String JSON_PROPERTY_APELLIDOS = "apellidos";
  @javax.annotation.Nullable
  private String apellidos;

  public static final String JSON_PROPERTY_APELLIDO1 = "apellido1";
  @javax.annotation.Nullable
  private String apellido1;

  public static final String JSON_PROPERTY_APELLIDO2 = "apellido2";
  @javax.annotation.Nullable
  private String apellido2;

  public RDatosRepresentante() {
  }

  public RDatosRepresentante nif(@javax.annotation.Nonnull String nif) {
    
    this.nif = nif;
    return this;
  }

  /**
   * Nif
   * @return nif
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NIF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNif() {
    return nif;
  }


  @JsonProperty(JSON_PROPERTY_NIF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNif(@javax.annotation.Nonnull String nif) {
    this.nif = nif;
  }

  public RDatosRepresentante nombre(@javax.annotation.Nonnull String nombre) {
    
    this.nombre = nombre;
    return this;
  }

  /**
   * Nombre
   * @return nombre
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NOMBRE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNombre() {
    return nombre;
  }


  @JsonProperty(JSON_PROPERTY_NOMBRE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNombre(@javax.annotation.Nonnull String nombre) {
    this.nombre = nombre;
  }

  public RDatosRepresentante apellidos(@javax.annotation.Nullable String apellidos) {
    
    this.apellidos = apellidos;
    return this;
  }

  /**
   * Apellidos
   * @return apellidos
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APELLIDOS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getApellidos() {
    return apellidos;
  }


  @JsonProperty(JSON_PROPERTY_APELLIDOS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApellidos(@javax.annotation.Nullable String apellidos) {
    this.apellidos = apellidos;
  }

  public RDatosRepresentante apellido1(@javax.annotation.Nullable String apellido1) {
    
    this.apellido1 = apellido1;
    return this;
  }

  /**
   * Apellido 1
   * @return apellido1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APELLIDO1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getApellido1() {
    return apellido1;
  }


  @JsonProperty(JSON_PROPERTY_APELLIDO1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApellido1(@javax.annotation.Nullable String apellido1) {
    this.apellido1 = apellido1;
  }

  public RDatosRepresentante apellido2(@javax.annotation.Nullable String apellido2) {
    
    this.apellido2 = apellido2;
    return this;
  }

  /**
   * Apellido 2
   * @return apellido2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APELLIDO2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getApellido2() {
    return apellido2;
  }


  @JsonProperty(JSON_PROPERTY_APELLIDO2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApellido2(@javax.annotation.Nullable String apellido2) {
    this.apellido2 = apellido2;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RDatosRepresentante rdatosRepresentante = (RDatosRepresentante) o;
    return Objects.equals(this.nif, rdatosRepresentante.nif) &&
        Objects.equals(this.nombre, rdatosRepresentante.nombre) &&
        Objects.equals(this.apellidos, rdatosRepresentante.apellidos) &&
        Objects.equals(this.apellido1, rdatosRepresentante.apellido1) &&
        Objects.equals(this.apellido2, rdatosRepresentante.apellido2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nif, nombre, apellidos, apellido1, apellido2);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RDatosRepresentante {\n");
    sb.append("    nif: ").append(toIndentedString(nif)).append("\n");
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    apellidos: ").append(toIndentedString(apellidos)).append("\n");
    sb.append("    apellido1: ").append(toIndentedString(apellido1)).append("\n");
    sb.append("    apellido2: ").append(toIndentedString(apellido2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

