/*
 * LoginIB API REST v1
 * API REST per interactuar amb el servei de LoginIB.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.login.loginib.api.client.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.fundaciobit.pluginsib.login.loginib.api.client.v1.model.RPropiedad;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * REvidenciasAutenticacion
 */
@JsonPropertyOrder({
  REvidenciasAutenticacion.JSON_PROPERTY_EVIDENCIAS,
  REvidenciasAutenticacion.JSON_PROPERTY_HUELLA_ELECTRONICA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class REvidenciasAutenticacion {
  public static final String JSON_PROPERTY_EVIDENCIAS = "evidencias";
  @javax.annotation.Nonnull
  private List<RPropiedad> evidencias = new ArrayList<>();

  public static final String JSON_PROPERTY_HUELLA_ELECTRONICA = "huellaElectronica";
  @javax.annotation.Nonnull
  private String huellaElectronica;

  public REvidenciasAutenticacion() {
  }

  public REvidenciasAutenticacion evidencias(@javax.annotation.Nonnull List<RPropiedad> evidencias) {
    
    this.evidencias = evidencias;
    return this;
  }

  public REvidenciasAutenticacion addEvidenciasItem(RPropiedad evidenciasItem) {
    if (this.evidencias == null) {
      this.evidencias = new ArrayList<>();
    }
    this.evidencias.add(evidenciasItem);
    return this;
  }

  /**
   * Lista de evidencias
   * @return evidencias
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EVIDENCIAS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<RPropiedad> getEvidencias() {
    return evidencias;
  }


  @JsonProperty(JSON_PROPERTY_EVIDENCIAS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEvidencias(@javax.annotation.Nonnull List<RPropiedad> evidencias) {
    this.evidencias = evidencias;
  }

  public REvidenciasAutenticacion huellaElectronica(@javax.annotation.Nonnull String huellaElectronica) {
    
    this.huellaElectronica = huellaElectronica;
    return this;
  }

  /**
   * Huella electrónica autenticación
   * @return huellaElectronica
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HUELLA_ELECTRONICA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getHuellaElectronica() {
    return huellaElectronica;
  }


  @JsonProperty(JSON_PROPERTY_HUELLA_ELECTRONICA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHuellaElectronica(@javax.annotation.Nonnull String huellaElectronica) {
    this.huellaElectronica = huellaElectronica;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    REvidenciasAutenticacion revidenciasAutenticacion = (REvidenciasAutenticacion) o;
    return Objects.equals(this.evidencias, revidenciasAutenticacion.evidencias) &&
        Objects.equals(this.huellaElectronica, revidenciasAutenticacion.huellaElectronica);
  }

  @Override
  public int hashCode() {
    return Objects.hash(evidencias, huellaElectronica);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class REvidenciasAutenticacion {\n");
    sb.append("    evidencias: ").append(toIndentedString(evidencias)).append("\n");
    sb.append("    huellaElectronica: ").append(toIndentedString(huellaElectronica)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

