/*
 * LoginIB API REST v1
 * API REST per interactuar amb el servei de LoginIB.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.login.loginib.api.client.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.fundaciobit.pluginsib.login.loginib.api.client.v1.model.RParamsApp;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Datos para iniciar proceso de inicio de sesión
 */
@JsonPropertyOrder({
  RLoginParams.JSON_PROPERTY_ENTIDAD,
  RLoginParams.JSON_PROPERTY_URL_CALLBACK,
  RLoginParams.JSON_PROPERTY_URL_CALLBACK_ERROR,
  RLoginParams.JSON_PROPERTY_METODOS_AUTENTICACION,
  RLoginParams.JSON_PROPERTY_QAA,
  RLoginParams.JSON_PROPERTY_IDIOMA,
  RLoginParams.JSON_PROPERTY_INICIO_CLAVE_AUTOMATICO,
  RLoginParams.JSON_PROPERTY_FORZAR_AUTENTICACION,
  RLoginParams.JSON_PROPERTY_APLICACION,
  RLoginParams.JSON_PROPERTY_AUDITAR,
  RLoginParams.JSON_PROPERTY_PARAMS_APP
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RLoginParams {
  public static final String JSON_PROPERTY_ENTIDAD = "entidad";
  @javax.annotation.Nonnull
  private String entidad;

  public static final String JSON_PROPERTY_URL_CALLBACK = "urlCallback";
  @javax.annotation.Nonnull
  private String urlCallback;

  public static final String JSON_PROPERTY_URL_CALLBACK_ERROR = "urlCallbackError";
  @javax.annotation.Nonnull
  private String urlCallbackError;

  public static final String JSON_PROPERTY_METODOS_AUTENTICACION = "metodosAutenticacion";
  @javax.annotation.Nonnull
  private String metodosAutenticacion;

  public static final String JSON_PROPERTY_QAA = "qaa";
  @javax.annotation.Nullable
  private Integer qaa;

  public static final String JSON_PROPERTY_IDIOMA = "idioma";
  @javax.annotation.Nonnull
  private String idioma;

  public static final String JSON_PROPERTY_INICIO_CLAVE_AUTOMATICO = "inicioClaveAutomatico";
  @javax.annotation.Nonnull
  private Boolean inicioClaveAutomatico;

  public static final String JSON_PROPERTY_FORZAR_AUTENTICACION = "forzarAutenticacion";
  @javax.annotation.Nonnull
  private Boolean forzarAutenticacion;

  public static final String JSON_PROPERTY_APLICACION = "aplicacion";
  @javax.annotation.Nullable
  private String aplicacion;

  public static final String JSON_PROPERTY_AUDITAR = "auditar";
  @javax.annotation.Nullable
  private Boolean auditar;

  public static final String JSON_PROPERTY_PARAMS_APP = "paramsApp";
  @javax.annotation.Nullable
  private RParamsApp paramsApp;

  public RLoginParams() {
  }

  public RLoginParams entidad(@javax.annotation.Nonnull String entidad) {
    
    this.entidad = entidad;
    return this;
  }

  /**
   * Código Entidad (DIR3)
   * @return entidad
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ENTIDAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEntidad() {
    return entidad;
  }


  @JsonProperty(JSON_PROPERTY_ENTIDAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEntidad(@javax.annotation.Nonnull String entidad) {
    this.entidad = entidad;
  }

  public RLoginParams urlCallback(@javax.annotation.Nonnull String urlCallback) {
    
    this.urlCallback = urlCallback;
    return this;
  }

  /**
   * Url Callback login
   * @return urlCallback
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_URL_CALLBACK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrlCallback() {
    return urlCallback;
  }


  @JsonProperty(JSON_PROPERTY_URL_CALLBACK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrlCallback(@javax.annotation.Nonnull String urlCallback) {
    this.urlCallback = urlCallback;
  }

  public RLoginParams urlCallbackError(@javax.annotation.Nonnull String urlCallbackError) {
    
    this.urlCallbackError = urlCallbackError;
    return this;
  }

  /**
   * Url Callback error
   * @return urlCallbackError
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_URL_CALLBACK_ERROR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrlCallbackError() {
    return urlCallbackError;
  }


  @JsonProperty(JSON_PROPERTY_URL_CALLBACK_ERROR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrlCallbackError(@javax.annotation.Nonnull String urlCallbackError) {
    this.urlCallbackError = urlCallbackError;
  }

  public RLoginParams metodosAutenticacion(@javax.annotation.Nonnull String metodosAutenticacion) {
    
    this.metodosAutenticacion = metodosAutenticacion;
    return this;
  }

  /**
   * Metodos autenticacion clave (separados por ;). Valores: ANONIMO;CLAVE_CERTIFICADO;CLAVE_PIN;CLAVE_PERMANENTE;CLAVE_MOVIL;CLIENTCERT;USUARIO_PASSWORD
   * @return metodosAutenticacion
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_METODOS_AUTENTICACION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMetodosAutenticacion() {
    return metodosAutenticacion;
  }


  @JsonProperty(JSON_PROPERTY_METODOS_AUTENTICACION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMetodosAutenticacion(@javax.annotation.Nonnull String metodosAutenticacion) {
    this.metodosAutenticacion = metodosAutenticacion;
  }

  public RLoginParams qaa(@javax.annotation.Nullable Integer qaa) {
    
    this.qaa = qaa;
    return this;
  }

  /**
   * Nivel autenticacion: 1 (Bajo), 2 (Medio) y 3 (Alto).
   * @return qaa
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QAA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getQaa() {
    return qaa;
  }


  @JsonProperty(JSON_PROPERTY_QAA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQaa(@javax.annotation.Nullable Integer qaa) {
    this.qaa = qaa;
  }

  public RLoginParams idioma(@javax.annotation.Nonnull String idioma) {
    
    this.idioma = idioma;
    return this;
  }

  /**
   * Idioma
   * @return idioma
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IDIOMA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIdioma() {
    return idioma;
  }


  @JsonProperty(JSON_PROPERTY_IDIOMA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdioma(@javax.annotation.Nonnull String idioma) {
    this.idioma = idioma;
  }

  public RLoginParams inicioClaveAutomatico(@javax.annotation.Nonnull Boolean inicioClaveAutomatico) {
    
    this.inicioClaveAutomatico = inicioClaveAutomatico;
    return this;
  }

  /**
   * Iniciar Cl@ve automatico
   * @return inicioClaveAutomatico
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INICIO_CLAVE_AUTOMATICO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getInicioClaveAutomatico() {
    return inicioClaveAutomatico;
  }


  @JsonProperty(JSON_PROPERTY_INICIO_CLAVE_AUTOMATICO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInicioClaveAutomatico(@javax.annotation.Nonnull Boolean inicioClaveAutomatico) {
    this.inicioClaveAutomatico = inicioClaveAutomatico;
  }

  public RLoginParams forzarAutenticacion(@javax.annotation.Nonnull Boolean forzarAutenticacion) {
    
    this.forzarAutenticacion = forzarAutenticacion;
    return this;
  }

  /**
   * Forzar autenticación
   * @return forzarAutenticacion
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FORZAR_AUTENTICACION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getForzarAutenticacion() {
    return forzarAutenticacion;
  }


  @JsonProperty(JSON_PROPERTY_FORZAR_AUTENTICACION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setForzarAutenticacion(@javax.annotation.Nonnull Boolean forzarAutenticacion) {
    this.forzarAutenticacion = forzarAutenticacion;
  }

  public RLoginParams aplicacion(@javax.annotation.Nullable String aplicacion) {
    
    this.aplicacion = aplicacion;
    return this;
  }

  /**
   * Aplicación
   * @return aplicacion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APLICACION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAplicacion() {
    return aplicacion;
  }


  @JsonProperty(JSON_PROPERTY_APLICACION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAplicacion(@javax.annotation.Nullable String aplicacion) {
    this.aplicacion = aplicacion;
  }

  public RLoginParams auditar(@javax.annotation.Nullable Boolean auditar) {
    
    this.auditar = auditar;
    return this;
  }

  /**
   * Indica si genera auditoría autenticación (con evidencias autenticación)
   * @return auditar
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUDITAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAuditar() {
    return auditar;
  }


  @JsonProperty(JSON_PROPERTY_AUDITAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuditar(@javax.annotation.Nullable Boolean auditar) {
    this.auditar = auditar;
  }

  public RLoginParams paramsApp(@javax.annotation.Nullable RParamsApp paramsApp) {
    
    this.paramsApp = paramsApp;
    return this;
  }

  /**
   * Get paramsApp
   * @return paramsApp
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARAMS_APP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RParamsApp getParamsApp() {
    return paramsApp;
  }


  @JsonProperty(JSON_PROPERTY_PARAMS_APP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParamsApp(@javax.annotation.Nullable RParamsApp paramsApp) {
    this.paramsApp = paramsApp;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RLoginParams rloginParams = (RLoginParams) o;
    return Objects.equals(this.entidad, rloginParams.entidad) &&
        Objects.equals(this.urlCallback, rloginParams.urlCallback) &&
        Objects.equals(this.urlCallbackError, rloginParams.urlCallbackError) &&
        Objects.equals(this.metodosAutenticacion, rloginParams.metodosAutenticacion) &&
        Objects.equals(this.qaa, rloginParams.qaa) &&
        Objects.equals(this.idioma, rloginParams.idioma) &&
        Objects.equals(this.inicioClaveAutomatico, rloginParams.inicioClaveAutomatico) &&
        Objects.equals(this.forzarAutenticacion, rloginParams.forzarAutenticacion) &&
        Objects.equals(this.aplicacion, rloginParams.aplicacion) &&
        Objects.equals(this.auditar, rloginParams.auditar) &&
        Objects.equals(this.paramsApp, rloginParams.paramsApp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entidad, urlCallback, urlCallbackError, metodosAutenticacion, qaa, idioma, inicioClaveAutomatico, forzarAutenticacion, aplicacion, auditar, paramsApp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RLoginParams {\n");
    sb.append("    entidad: ").append(toIndentedString(entidad)).append("\n");
    sb.append("    urlCallback: ").append(toIndentedString(urlCallback)).append("\n");
    sb.append("    urlCallbackError: ").append(toIndentedString(urlCallbackError)).append("\n");
    sb.append("    metodosAutenticacion: ").append(toIndentedString(metodosAutenticacion)).append("\n");
    sb.append("    qaa: ").append(toIndentedString(qaa)).append("\n");
    sb.append("    idioma: ").append(toIndentedString(idioma)).append("\n");
    sb.append("    inicioClaveAutomatico: ").append(toIndentedString(inicioClaveAutomatico)).append("\n");
    sb.append("    forzarAutenticacion: ").append(toIndentedString(forzarAutenticacion)).append("\n");
    sb.append("    aplicacion: ").append(toIndentedString(aplicacion)).append("\n");
    sb.append("    auditar: ").append(toIndentedString(auditar)).append("\n");
    sb.append("    paramsApp: ").append(toIndentedString(paramsApp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

