/*
 * LoginIB API REST v1
 * API REST per interactuar amb el servei de LoginIB.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.login.loginib.api.client.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Parámetros logout
 */
@JsonPropertyOrder({
  RLogoutParams.JSON_PROPERTY_ENTIDAD,
  RLogoutParams.JSON_PROPERTY_URL_CALLBACK,
  RLogoutParams.JSON_PROPERTY_IDIOMA,
  RLogoutParams.JSON_PROPERTY_APLICACION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RLogoutParams {
  public static final String JSON_PROPERTY_ENTIDAD = "entidad";
  @javax.annotation.Nonnull
  private String entidad;

  public static final String JSON_PROPERTY_URL_CALLBACK = "urlCallback";
  @javax.annotation.Nonnull
  private String urlCallback;

  public static final String JSON_PROPERTY_IDIOMA = "idioma";
  @javax.annotation.Nonnull
  private String idioma;

  public static final String JSON_PROPERTY_APLICACION = "aplicacion";
  @javax.annotation.Nonnull
  private String aplicacion;

  public RLogoutParams() {
  }

  public RLogoutParams entidad(@javax.annotation.Nonnull String entidad) {
    
    this.entidad = entidad;
    return this;
  }

  /**
   * Código Entidad (DIR3)
   * @return entidad
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ENTIDAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEntidad() {
    return entidad;
  }


  @JsonProperty(JSON_PROPERTY_ENTIDAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEntidad(@javax.annotation.Nonnull String entidad) {
    this.entidad = entidad;
  }

  public RLogoutParams urlCallback(@javax.annotation.Nonnull String urlCallback) {
    
    this.urlCallback = urlCallback;
    return this;
  }

  /**
   * Url Callback
   * @return urlCallback
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_URL_CALLBACK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrlCallback() {
    return urlCallback;
  }


  @JsonProperty(JSON_PROPERTY_URL_CALLBACK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrlCallback(@javax.annotation.Nonnull String urlCallback) {
    this.urlCallback = urlCallback;
  }

  public RLogoutParams idioma(@javax.annotation.Nonnull String idioma) {
    
    this.idioma = idioma;
    return this;
  }

  /**
   * Idioma
   * @return idioma
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IDIOMA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIdioma() {
    return idioma;
  }


  @JsonProperty(JSON_PROPERTY_IDIOMA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdioma(@javax.annotation.Nonnull String idioma) {
    this.idioma = idioma;
  }

  public RLogoutParams aplicacion(@javax.annotation.Nonnull String aplicacion) {
    
    this.aplicacion = aplicacion;
    return this;
  }

  /**
   * Aplicacion
   * @return aplicacion
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_APLICACION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAplicacion() {
    return aplicacion;
  }


  @JsonProperty(JSON_PROPERTY_APLICACION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAplicacion(@javax.annotation.Nonnull String aplicacion) {
    this.aplicacion = aplicacion;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RLogoutParams rlogoutParams = (RLogoutParams) o;
    return Objects.equals(this.entidad, rlogoutParams.entidad) &&
        Objects.equals(this.urlCallback, rlogoutParams.urlCallback) &&
        Objects.equals(this.idioma, rlogoutParams.idioma) &&
        Objects.equals(this.aplicacion, rlogoutParams.aplicacion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entidad, urlCallback, idioma, aplicacion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RLogoutParams {\n");
    sb.append("    entidad: ").append(toIndentedString(entidad)).append("\n");
    sb.append("    urlCallback: ").append(toIndentedString(urlCallback)).append("\n");
    sb.append("    idioma: ").append(toIndentedString(idioma)).append("\n");
    sb.append("    aplicacion: ").append(toIndentedString(aplicacion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

