/*
 * LoginIB API REST v1
 * API REST per interactuar amb el servei de LoginIB.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.login.loginib.api.client.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.fundaciobit.pluginsib.login.loginib.api.client.v1.model.RParamApp;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Parametros extras de la peticion
 */
@JsonPropertyOrder({
  RParamsApp.JSON_PROPERTY_PARAMETROS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RParamsApp {
  public static final String JSON_PROPERTY_PARAMETROS = "parametros";
  @javax.annotation.Nonnull
  private List<RParamApp> parametros = new ArrayList<>();

  public RParamsApp() {
  }

  public RParamsApp parametros(@javax.annotation.Nonnull List<RParamApp> parametros) {
    
    this.parametros = parametros;
    return this;
  }

  public RParamsApp addParametrosItem(RParamApp parametrosItem) {
    if (this.parametros == null) {
      this.parametros = new ArrayList<>();
    }
    this.parametros.add(parametrosItem);
    return this;
  }

  /**
   * Parametros
   * @return parametros
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PARAMETROS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<RParamApp> getParametros() {
    return parametros;
  }


  @JsonProperty(JSON_PROPERTY_PARAMETROS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParametros(@javax.annotation.Nonnull List<RParamApp> parametros) {
    this.parametros = parametros;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RParamsApp rparamsApp = (RParamsApp) o;
    return Objects.equals(this.parametros, rparamsApp.parametros);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parametros);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RParamsApp {\n");
    sb.append("    parametros: ").append(toIndentedString(parametros)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

