/*
 * LoginIB API REST v1
 * API REST per interactuar amb el servei de LoginIB.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.pluginsib.login.loginib.api.client.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Lista de evidencias
 */
@JsonPropertyOrder({
  RPropiedad.JSON_PROPERTY_PROPIEDAD,
  RPropiedad.JSON_PROPERTY_TIPO,
  RPropiedad.JSON_PROPERTY_VALOR,
  RPropiedad.JSON_PROPERTY_MOSTRAR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RPropiedad {
  public static final String JSON_PROPERTY_PROPIEDAD = "propiedad";
  @javax.annotation.Nonnull
  private String propiedad;

  public static final String JSON_PROPERTY_TIPO = "tipo";
  @javax.annotation.Nonnull
  private String tipo;

  public static final String JSON_PROPERTY_VALOR = "valor";
  @javax.annotation.Nonnull
  private String valor;

  public static final String JSON_PROPERTY_MOSTRAR = "mostrar";
  @javax.annotation.Nonnull
  private Boolean mostrar;

  public RPropiedad() {
  }

  public RPropiedad propiedad(@javax.annotation.Nonnull String propiedad) {
    
    this.propiedad = propiedad;
    return this;
  }

  /**
   * Propiedad
   * @return propiedad
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROPIEDAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPropiedad() {
    return propiedad;
  }


  @JsonProperty(JSON_PROPERTY_PROPIEDAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPropiedad(@javax.annotation.Nonnull String propiedad) {
    this.propiedad = propiedad;
  }

  public RPropiedad tipo(@javax.annotation.Nonnull String tipo) {
    
    this.tipo = tipo;
    return this;
  }

  /**
   * Tipo: String / XML (Base64)
   * @return tipo
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TIPO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTipo() {
    return tipo;
  }


  @JsonProperty(JSON_PROPERTY_TIPO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTipo(@javax.annotation.Nonnull String tipo) {
    this.tipo = tipo;
  }

  public RPropiedad valor(@javax.annotation.Nonnull String valor) {
    
    this.valor = valor;
    return this;
  }

  /**
   * Valor
   * @return valor
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getValor() {
    return valor;
  }


  @JsonProperty(JSON_PROPERTY_VALOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValor(@javax.annotation.Nonnull String valor) {
    this.valor = valor;
  }

  public RPropiedad mostrar(@javax.annotation.Nonnull Boolean mostrar) {
    
    this.mostrar = mostrar;
    return this;
  }

  /**
   * Valor
   * @return mostrar
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MOSTRAR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getMostrar() {
    return mostrar;
  }


  @JsonProperty(JSON_PROPERTY_MOSTRAR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMostrar(@javax.annotation.Nonnull Boolean mostrar) {
    this.mostrar = mostrar;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RPropiedad rpropiedad = (RPropiedad) o;
    return Objects.equals(this.propiedad, rpropiedad.propiedad) &&
        Objects.equals(this.tipo, rpropiedad.tipo) &&
        Objects.equals(this.valor, rpropiedad.valor) &&
        Objects.equals(this.mostrar, rpropiedad.mostrar);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propiedad, tipo, valor, mostrar);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RPropiedad {\n");
    sb.append("    propiedad: ").append(toIndentedString(propiedad)).append("\n");
    sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("    mostrar: ").append(toIndentedString(mostrar)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

