/*
 * LoginIB API REST v1
 * API REST per interactuar amb el servei de LoginIB.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.fundaciobit.pluginsib.login.loginib.api.client.v1.api;

import org.fundaciobit.pluginsib.login.loginib.api.client.v1.services.ApiClient;
import org.fundaciobit.pluginsib.login.loginib.api.client.v1.services.ApiException;
import org.jboss.logging.Logger;
import org.fundaciobit.pluginsib.login.loginib.api.client.v1.model.RDatosAutenticacion;
import org.fundaciobit.pluginsib.login.loginib.api.client.v1.model.REvidenciasAutenticacion;
import org.fundaciobit.pluginsib.login.loginib.api.client.v1.model.RLoginParams;
import org.fundaciobit.pluginsib.login.loginib.api.client.v1.model.RPropiedad;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.FileInputStream;
import java.util.Properties;

/**
 * API tests for LoginIbv1Api
 */
class LoginIbv1ApiTest {

    //private final LoginIbv1Api api = new LoginIbv1Api();

    static Logger log = Logger.getLogger(LoginIbv1ApiTest.class);

    public static void main(String[] args) {

        try {

            LoginIbv1ApiTest test = new LoginIbv1ApiTest();

            LoginIbv1Api api = test.getApi();

            // Cercar un port de xarxa lliure ...
            int port = 1234;
            {
                boolean portLibre = false;
                while (!portLibre) {
                    try {
                        java.net.ServerSocket serverSocket = new java.net.ServerSocket(port);
                        serverSocket.close();
                        portLibre = true;
                    } catch (java.net.BindException e) {
                        port++;
                    }
                }
            }

            String urlredirect = test.startAuthentication(api, "http://localhost:" + port + "/loginib/callbackok",
                    "http://localhost:" + port + "/loginib/callbackerror", "ca");

            log.info("URL REDIRECT: " + urlredirect);

            // https://se.caib.es/loginibfront/seleccionAutenticacion.html?idioma=ca&idSesion=VJB6BDB1-05LUR8T8-T8KZF4CL
            // Extreure idSesion de la URL de redirecció.
            String idSesion = null;
            int index = urlredirect.lastIndexOf("idSesion=");
            if (index != -1) {
                idSesion = urlredirect.substring(index + "idSesion=".length());
            }

            log.info("ID Session: " + idSesion);

            // Obrir un navegador amb la URL de redirecció per iniciar el procés d'autenticació
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(urlredirect));

            // Escoltar amb un ServerSocket al port "portLibre" i imprimir la recepció. Despres de rebre continuar.
            java.net.ServerSocket serverSocket = new java.net.ServerSocket(port);
            log.info("Esperant connexió al port " + port + " ...");
            java.net.Socket socket = serverSocket.accept();
            log.info("Connexió rebuda al port " + port + " ...");
            java.io.BufferedReader in = new java.io.BufferedReader(
                    new java.io.InputStreamReader(socket.getInputStream()));
            String line;

            StringBuilder requestBuilder = new StringBuilder();
            Boolean isOK = null;
            while ((line = in.readLine()) != null) {
                //log.info("Rebut: " + line);
                requestBuilder.append(line).append("\n");
                if (line.contains("/loginib/callbackok")) {
                    isOK = true;
                    break;
                }

                if (line.contains("GET /loginib/callbackerror")) {
                    isOK = false;
                }
            }

            // Contestar amb una resposta HTTP 200 OK i un missatge "Revisar consola de test per veure el resultat de l'autenticació"

            java.io.PrintWriter out = new java.io.PrintWriter(socket.getOutputStream(), true);
            out.println("HTTP/1.1 200 OK");
            out.println("Content-Type: text/plain");
            out.println();
            out.println("Revisar consola de test per veure el resultat de l'autenticaci&oacute;.");
            out.flush();

            out.close();

            in.close();
            socket.close();
            serverSocket.close();

            if (isOK == null || isOK == false) {
                log.info(
                        "Autenticació no realitzada o error en autenticació: RESPOSTA:\n " + requestBuilder.toString());
                return;
            }
            
            
           RDatosAutenticacion da =  api.ticket(idSesion);
           log.info("Dades autenticació: " + da);
            
            

            REvidenciasAutenticacion evis = api.evidencias(idSesion);
            
            

            log.info("Huella: " + evis.getHuellaElectronica());

            for (RPropiedad evidencia : evis.getEvidencias()) {
                log.info("Evidencia: " + evidencia);
            }

        } catch (Exception e) {
            // TODO: handle exception
            e.printStackTrace();
        }

    }

    public static final String PLUGIN_LOGINIB_PROPERTY_BASE = "es.caib.evidenciesib.pluginsib.login.loginib.";

    public Properties getProperties() throws Exception {

        Properties properties = new Properties();

        properties.load(new FileInputStream(new File("test.properties")));

        return properties;
    }

    public String startAuthentication(LoginIbv1Api api, String urlCallBackLoginOk, String urCallBackLoginError,
            String language) throws Exception {

        log.info("  PluginLoginLoginIB::startAuthentication() ENTRA ... ");

        final RLoginParams param = new RLoginParams();
        param.setAplicacion(getLoginIBAplicacionCode());
        param.setEntidad(getLoginIBEntidad());
        param.setUrlCallback(urlCallBackLoginOk);
        param.setUrlCallbackError(urCallBackLoginError);
        param.setIdioma(language);
        param.setForzarAutenticacion(false);
        param.setQaa(Integer.parseInt(getLoginIBNivelQAA()));
        param.setMetodosAutenticacion(getLoginIBMethodAuth());
        param.setAplicacion(getLoginIBAplicacionCode());
        param.setInicioClaveAutomatico(true);
        param.setAuditar(true);

        String urlredirect = api.login(param);

        /* RestTemplate Spring */
        /*
        final org.springframework.web.client.RestTemplate restTemplate = getLoginIbRestTemplate();
        
        final org.springframework.http.HttpHeaders headers = new org.springframework.http.HttpHeaders();
        headers.setContentType(org.springframework.http.MediaType.APPLICATION_JSON);
        
        log.info("\n\n\nAUDITAR TRUE !!!!!!!!!!!!!! \n\n\n");
        
        final org.springframework.http.HttpEntity<RLoginParams> peticion;
        peticion = new org.springframework.http.HttpEntity<>(param, headers);
        final org.springframework.http.ResponseEntity<String> responseLoginIB = restTemplate
                .postForEntity(getLoginIBUrl() + "/login", peticion, String.class);
                */

        log.info("LoginIB: response: " + urlredirect);

        return urlredirect;

    }

    public LoginIbv1Api getApi() throws Exception {
        ApiClient client = new ApiClient();
        client.setBasePath(getLoginIBUrl());

        client.setUsername(getLoginIBUser());
        client.setPassword(getLoginIBPassword());

        LoginIbv1Api api = new LoginIbv1Api(client);
        return api;
    }

    protected String getLoginIBMethodAuth() throws Exception {
        return getProperties().getProperty(PLUGIN_LOGINIB_PROPERTY_BASE + "metodos_auth");
    }

    protected String getLoginIBEntidad() throws Exception {
        return getProperties().getProperty(PLUGIN_LOGINIB_PROPERTY_BASE + "entidad");
    }

    protected String getLoginIBAplicacionCode() throws Exception {
        return getProperties().getProperty(PLUGIN_LOGINIB_PROPERTY_BASE + "aplicacion");
    }

    protected String getLoginIBAplicacionDescription() throws Exception {
        return getProperties().getProperty(PLUGIN_LOGINIB_PROPERTY_BASE + "aplicaciondescripcion");
    }

    protected String getLoginIBNivelQAA() throws Exception {
        return getProperties().getProperty(PLUGIN_LOGINIB_PROPERTY_BASE + "nivel_qaa");
    }

    protected String getLoginIBUser() throws Exception {
        return getProperties().getProperty(PLUGIN_LOGINIB_PROPERTY_BASE + "user");
    }

    protected String getLoginIBPassword() throws Exception {
        return getProperties().getProperty(PLUGIN_LOGINIB_PROPERTY_BASE + "pass");
    }

    protected String getLoginIBUrl() throws Exception {
        return getProperties().getProperty(PLUGIN_LOGINIB_PROPERTY_BASE + "url");
    }

    /**
     * Iniciar proceso de inicio de sesión
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void loginTest() throws ApiException {
        //
        //RLoginParams rloginParams = null;
        //
        //String response = api.login(rloginParams);

        // TODO: test validations
    }

    /**
     * Realiza logout en Cl@ve
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void logoutTest() throws ApiException {
        //
        //RLogoutParams rlogoutParams = null;
        //
        //String response = api.logout(rlogoutParams);

        // TODO: test validations
    }

    /**
     * Obtener evidencias autenticación
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void logout1Test() throws ApiException {
        //
        //String idSesion = null;
        //
        //String body = null;
        //
        //REvidenciasAutenticacion response = api.logout1(idSesion, body);

        // TODO: test validations
    }

    /**
     * Obtiene datos autenticación a partir del ticket
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void ticketTest() throws ApiException {
        //
        //String ticket = null;
        //
        //String body = null;
        //
        //RDatosAutenticacion response = api.ticket(ticket, body);

        // TODO: test validations
    }
}
